<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType><TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms><UseWPF>true</UseWPF>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../../src/Kazrich.App/Kazrich.App.csproj" /></ItemGroup>
</Project>
