<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>RichType</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>0.8.33</Version>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../Kazrich.Core/Kazrich.Core.csproj" /></ItemGroup>
</Project>
